#coding:utf8

ext2mime_table='''
.xlsx   application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
.xltx   application/vnd.openxmlformats-officedocument.spreadsheetml.template
.potx   application/vnd.openxmlformats-officedocument.presentationml.template
.ppsx   application/vnd.openxmlformats-officedocument.presentationml.slideshow
.pptx   application/vnd.openxmlformats-officedocument.presentationml.presentation
.sldx   application/vnd.openxmlformats-officedocument.presentationml.slide
.docx   application/vnd.openxmlformats-officedocument.wordprocessingml.document
.dotx   application/vnd.openxmlformats-officedocument.wordprocessingml.template
.xlam   application/vnd.ms-excel.addin.macroEnabled.12
.xlsb   application/vnd.ms-excel.sheet.binary.macroEnabled.12
.3dm                                              x-world/x-3dmf
.3dmf                                             x-world/x-3dmf
.a                                                application/octet-stream
.aab                                              application/x-authorware-bin
.aam                                              application/x-authorware-map
.aas                                              application/x-authorware-seg
.abc                                              text/vnd.abc
.acgi                                             text/html
.afl                                              video/animaflex
.ai                                               application/postscript
.aif                                              audio/aiff
.aif                                              audio/x-aiff
.aifc                                             audio/aiff
.aifc                                             audio/x-aiff
.aiff                                             audio/aiff
.aiff                                             audio/x-aiff
.aim                                              application/x-aim
.aip                                              text/x-audiosoft-intra
.ani                                              application/x-navi-animation
.aos                                              application/x-nokia-9000-communicator-add-on-software
.aps                                              application/mime
.arc                                              application/octet-stream
.arj                                              application/arj
.arj                                              application/octet-stream
.art                                              image/x-jg
.asf                                              video/x-ms-asf
.asm                                              text/x-asm
.asp                                              text/asp
.asx                                              application/x-mplayer2
.asx                                              video/x-ms-asf
.asx                                              video/x-ms-asf-plugin
.au                                               audio/basic
.au                                               audio/x-au
.avi                                              video/avi
.avi                                              application/x-troff-msvideo
.avi                                              video/msvideo
.avi                                              video/x-msvideo
.avs                                              video/avs-video
.bcpio                                            application/x-bcpio
.bin                                              application/octet-stream
.bin                                              application/mac-binary
.bin                                              application/macbinary
.bin                                              application/x-binary
.bin                                              application/x-macbinary
.bm                                               image/bmp
.bmp                                              image/bmp
.bmp                                              image/x-windows-bmp
.boo                                              application/book
.book                                             application/book
.boz                                              application/x-bzip2
.bsh                                              application/x-bsh
.bz                                               application/x-bzip
.bz2                                              application/x-bzip2
.c                                                text/x-c
.c                                                text/plain
.c++                                              text/plain
.cat                                              application/vnd.ms-pki.seccat
.cc                                               text/x-c
.cc                                               text/plain
.ccad                                             application/clariscad
.cco                                              application/x-cocoa
.cdf                                              application/cdf
.cdf                                              application/x-cdf
.cdf                                              application/x-netcdf
.cer                                              application/pkix-cert
.cer                                              application/x-x509-ca-cert
.cha                                              application/x-chat
.chat                                             application/x-chat
.class                                            application/java
.class                                            application/java-byte-code
.class                                            application/x-java-class
.com                                              application/octet-stream
.com                                              text/plain
.conf                                             text/plain
.cpio                                             application/x-cpio
.cpp                                              text/x-c
.cpt                                              application/mac-compactpro
.cpt                                              application/x-compactpro
.cpt                                              application/x-cpt
.crl                                              application/pkcs-crl
.crl                                              application/pkix-crl
.crt                                              application/pkix-cert
.crt                                              application/x-x509-ca-cert
.crt                                              application/x-x509-user-cert
.csh                                              application/x-csh
.csh                                              text/x-script.csh
.css                                              text/css
.css                                              application/x-pointplus
.cxx                                              text/plain
.dcr                                              application/x-director
.deepv                                            application/x-deepv
.def                                              text/plain
.der                                              application/x-x509-ca-cert
.dif                                              video/x-dv
.dir                                              application/x-director
.dl                                               video/dl
.dl                                               video/x-dl
.doc                                              application/msword
.dot                                              application/msword
.dp                                               application/commonground
.drw                                              application/drafting
.dump                                             application/octet-stream
.dv                                               video/x-dv
.dvi                                              application/x-dvi
.dwf                                              drawing/x-dwf
.dwf                                              model/vnd.dwf
.dwg                                              application/acad
.dwg                                              image/vnd.dwg
.dwg                                              image/x-dwg
.dxf                                              application/dxf
.dxf                                              image/vnd.dwg
.dxf                                              image/x-dwg
.dxr                                              application/x-director
.el                                               text/x-script.elisp
.elc                                              application/x-bytecode.elisp
.elc                                              application/x-elc
.env                                              application/x-envoy
.eps                                              application/postscript
.es                                               application/x-esrehber
.etx                                              text/x-setext
.evy                                              application/envoy
.evy                                              application/x-envoy
.exe                                              application/octet-stream
.f                                                text/x-fortran
.f                                                text/plain
.f77                                              text/x-fortran
.f90                                              text/x-fortran
.f90                                              text/plain
.fdf                                              application/vnd.fdf
.fif                                              image/fif
.fif                                              application/fractals
.fli                                              video/fli
.fli                                              video/x-fli
.flo                                              image/florian
.flx                                              text/vnd.fmi.flexstor
.fmf                                              video/x-atomic3d-feature
.for                                              text/x-fortran
.for                                              text/plain
.fpx                                              image/vnd.fpx
.fpx                                              image/vnd.net-fpx
.frl                                              application/freeloader
.funk                                             audio/make
.g                                                text/plain
.g3                                               image/g3fax
.gif                                              image/gif
.gl                                               video/gl
.gl                                               video/x-gl
.gsd                                              audio/x-gsm
.gsm                                              audio/x-gsm
.gsp                                              application/x-gsp
.gss                                              application/x-gss
.gtar                                             application/x-gtar
.gz                                               application/x-gzip
.gz                                               application/x-compressed
.gzip                                             application/x-gzip
.gzip                                             multipart/x-gzip
.h                                                text/x-h
.h                                                text/plain
.hdf                                              application/x-hdf
.help                                             application/x-helpfile
.hgl                                              application/vnd.hp-hpgl
.hh                                               text/x-h
.hh                                               text/plain
.hlb                                              text/x-script
.hlp                                              application/hlp
.hlp                                              application/x-helpfile
.hlp                                              application/x-winhelp
.hpg                                              application/vnd.hp-hpgl
.hpgl                                             application/vnd.hp-hpgl
.hqx                                              application/binhex
.hqx                                              application/binhex4
.hqx                                              application/mac-binhex
.hqx                                              application/mac-binhex40
.hqx                                              application/x-binhex40
.hqx                                              application/x-mac-binhex40
.hta                                              application/hta
.htc                                              text/x-component
.htm                                              text/html
.html                                             text/html
.htmls                                            text/html
.htt                                              text/webviewhtml
.htx                                              text/html
.ice                                              x-conference/x-cooltalk
.ico                                              image/x-icon
.idc                                              text/plain
.ief                                              image/ief
.iefs                                             image/ief
.iges                                             application/iges
.iges                                             model/iges
.igs                                              application/iges
.igs                                              model/iges
.ima                                              application/x-ima
.imap                                             application/x-httpd-imap
.inf                                              application/inf
.ins                                              application/x-internett-signup
.ip                                               application/x-ip2
.isu                                              video/x-isvideo
.it                                               audio/it
.iv                                               application/x-inventor
.ivr                                              i-world/i-vrml
.ivy                                              application/x-livescreen
.jam                                              audio/x-jam
.jav                                              text/plain
.jav                                              text/x-java-source
.java                                             text/plain
.java                                             text/x-java-source
.jcm                                              application/x-java-commerce
.jfif                                             image/jpeg
.jfif                                             image/pjpeg
.jfif-tbnl                                        image/jpeg
.jpe                                              image/jpeg
.jpe                                              image/pjpeg
.jpeg                                             image/jpeg
.jpeg                                             image/pjpeg
.jpg                                              image/jpeg
.jpg                                              image/pjpeg
.jps                                              image/x-jps
.js                                               application/x-javascript
.jut                                              image/jutvision
.kar                                              audio/midi
.kar                                              music/x-karaoke
.ksh                                              application/x-ksh
.ksh                                              text/x-script.ksh
.la                                               audio/nspaudio
.la                                               audio/x-nspaudio
.lam                                              audio/x-liveaudio
.latex                                            application/x-latex
.lha                                              application/lha
.lha                                              application/octet-stream
.lha                                              application/x-lha
.lhx                                              application/octet-stream
.list                                             text/plain
.lma                                              audio/nspaudio
.lma                                              audio/x-nspaudio
.log                                              text/plain
.lsp                                              application/x-lisp
.lsp                                              text/x-script.lisp
.lst                                              text/plain
.lsx                                              text/x-la-asf
.ltx                                              application/x-latex
.lzh                                              application/octet-stream
.lzh                                              application/x-lzh
.lzx                                              application/lzx
.lzx                                              application/octet-stream
.lzx                                              application/x-lzx
.m                                                text/plain
.m                                                text/x-m
.m1v                                              video/mpeg
.m2a                                              audio/mpeg
.m2v                                              video/mpeg
.m3u                                              audio/x-mpequrl
.man                                              application/x-troff-man
.map                                              application/x-navimap
.mar                                              text/plain
.mbd                                              application/mbedlet
.mc$                                              application/x-magic-cap-package-1.0
.mcd                                              application/mcad
.mcd                                              application/x-mathcad
.mcf                                              image/vasa
.mcf                                              text/mcf
.mcp                                              application/netmc
.me                                               application/x-troff-me
.mht                                              message/rfc822
.mhtml                                            message/rfc822
.mid                                              application/x-midi
.mid                                              audio/midi
.mid                                              audio/x-mid
.mid                                              audio/x-midi
.mid                                              music/crescendo
.mid                                              x-music/x-midi
.midi                                             application/x-midi
.midi                                             audio/midi
.midi                                             audio/x-mid
.midi                                             audio/x-midi
.midi                                             music/crescendo
.midi                                             x-music/x-midi
.mif                                              application/x-frame
.mif                                              application/x-mif
.mime                                             message/rfc822
.mime                                             www/mime
.mjf                                              audio/x-vnd.audioexplosion.mjuicemediafile
.mjpg                                             video/x-motion-jpeg
.mm                                               application/base64
.mm                                               application/x-meme
.mme                                              application/base64
.mod                                              audio/mod
.mod                                              audio/x-mod
.moov                                             video/quicktime
.mov                                              video/quicktime
.movie                                            video/x-sgi-movie
.mp2                                              audio/mpeg
.mp2                                              audio/x-mpeg
.mp2                                              video/mpeg
.mp2                                              video/x-mpeg
.mp2                                              video/x-mpeq2a
.mp3                                              audio/mpeg3
.mp3                                              audio/x-mpeg-3
.mp3                                              video/mpeg
.mp3                                              video/x-mpeg
.mpa                                              audio/mpeg
.mpa                                              video/mpeg
.mpc                                              application/x-project
.mpe                                              video/mpeg
.mpeg                                             video/mpeg
.mpg                                              video/mpeg
.mpg                                              audio/mpeg
.mpga                                             audio/mpeg
.mpp                                              application/vnd.ms-project
.mpt                                              application/x-project
.mpv                                              application/x-project
.mpx                                              application/x-project
.mrc                                              application/marc
.ms                                               application/x-troff-ms
.mv                                               video/x-sgi-movie
.my                                               audio/make
.mzz                                              application/x-vnd.audioexplosion.mzz
.nap                                              image/naplps
.naplps                                           image/naplps
.nc                                               application/x-netcdf
.ncm                                              application/vnd.nokia.configuration-message
.nif                                              image/x-niff
.niff                                             image/x-niff
.nix                                              application/x-mix-transfer
.nsc                                              application/x-conference
.nvd                                              application/x-navidoc
.o                                                application/octet-stream
.oda                                              application/oda
.omc                                              application/x-omc
.omcd                                             application/x-omcdatamaker
.omcr                                             application/x-omcregerator
.p                                                text/x-pascal
.p10                                              application/pkcs10
.p10                                              application/x-pkcs10
.p12                                              application/pkcs-12
.p12                                              application/x-pkcs12
.p7a                                              application/x-pkcs7-signature
.p7c                                              application/pkcs7-mime
.p7c                                              application/x-pkcs7-mime
.p7m                                              application/pkcs7-mime
.p7m                                              application/x-pkcs7-mime
.p7r                                              application/x-pkcs7-certreqresp
.p7s                                              application/pkcs7-signature
.part                                             application/pro_eng
.pas                                              text/pascal
.pbm                                              image/x-portable-bitmap
.pcl                                              application/vnd.hp-pcl
.pcl                                              application/x-pcl
.pct                                              image/x-pict
.pcx                                              image/x-pcx
.pdb                                              chemical/x-pdb
.pdf                                              application/pdf
.pfunk                                            audio/make
.pfunk                                            audio/make.my.funk
.pgm                                              image/x-portable-graymap
.pgm                                              image/x-portable-greymap
.pic                                              image/pict
.pict                                             image/pict
.pkg                                              application/x-newton-compatible-pkg
.pko                                              application/vnd.ms-pki.pko
.pl                                               text/plain
.pl                                               text/x-script.perl
.plx                                              application/x-pixclscript
.pm                                               image/x-xpixmap
.pm                                               text/x-script.perl-module
.pm4                                              application/x-pagemaker
.pm5                                              application/x-pagemaker
.png                                              image/png
.pnm                                              application/x-portable-anymap
.pnm                                              image/x-portable-anymap
.pot                                              application/mspowerpoint
.pot                                              application/vnd.ms-powerpoint
.pov                                              model/x-pov
.ppa                                              application/vnd.ms-powerpoint
.ppm                                              image/x-portable-pixmap
.pps                                              application/mspowerpoint
.pps                                              application/vnd.ms-powerpoint
.ppt                                              application/mspowerpoint
.ppt                                              application/powerpoint
.ppt                                              application/vnd.ms-powerpoint
.ppt                                              application/x-mspowerpoint
.ppz                                              application/mspowerpoint
.pre                                              application/x-freelance
.prt                                              application/pro_eng
.ps                                               application/postscript
.psd                                              application/octet-stream
.pvu                                              paleovu/x-pv
.pwz                                              application/vnd.ms-powerpoint
.py                                               text/x-script.phyton
.pyc                                              applicaiton/x-bytecode.python
.qcp                                              audio/vnd.qcelp
.qd3                                              x-world/x-3dmf
.qd3d                                             x-world/x-3dmf
.qif                                              image/x-quicktime
.qt                                               video/quicktime
.qtc                                              video/x-qtc
.qti                                              image/x-quicktime
.qtif                                             image/x-quicktime
.ra                                               audio/x-pn-realaudio
.ra                                               audio/x-pn-realaudio-plugin
.ra                                               audio/x-realaudio
.ram                                              audio/x-pn-realaudio
.rar							application/octet-stream
.ras                                              application/x-cmu-raster
.ras                                              image/cmu-raster
.ras                                              image/x-cmu-raster
.rast                                             image/cmu-raster
.rexx                                             text/x-script.rexx
.rf                                               image/vnd.rn-realflash
.rgb                                              image/x-rgb
.rm                                               application/vnd.rn-realmedia
.rm                                               audio/x-pn-realaudio
.rmi                                              audio/mid
.rmm                                              audio/x-pn-realaudio
.rmp                                              audio/x-pn-realaudio
.rmp                                              audio/x-pn-realaudio-plugin
.rng                                              application/ringing-tones
.rng                                              application/vnd.nokia.ringing-tone
.rnx                                              application/vnd.rn-realplayer
.roff                                             application/x-troff
.rp                                               image/vnd.rn-realpix
.rpm                                              audio/x-pn-realaudio-plugin
.rt                                               text/richtext
.rt                                               text/vnd.rn-realtext
.rtf                                              application/rtf
.rtf                                              application/x-rtf
.rtf                                              text/richtext
.rtx                                              application/rtf
.rtx                                              text/richtext
.rv                                               video/vnd.rn-realvideo
.s                                                text/x-asm
.s3m                                              audio/s3m
.saveme                                           application/octet-stream
.sbk                                              application/x-tbook
.scm                                              application/x-lotusscreencam
.scm                                              text/x-script.guile
.scm                                              text/x-script.scheme
.scm                                              video/x-scm
.sdml                                             text/plain
.sdp                                              application/sdp
.sdp                                              application/x-sdp
.sdr                                              application/sounder
.sea                                              application/sea
.sea                                              application/x-sea
.set                                              application/set
.sgm                                              text/sgml
.sgm                                              text/x-sgml
.sgml                                             text/sgml
.sgml                                             text/x-sgml
.sh                                               application/x-sh
.sh                                               application/x-bsh
.sh                                               application/x-shar
.sh                                               text/x-script.sh
.shar                                             application/x-bsh
.shar                                             application/x-shar
.shtml                                            text/html
.shtml                                            text/x-server-parsed-html
.sid                                              audio/x-psid
.sit                                              application/x-sit
.sit                                              application/x-stuffit
.skd                                              application/x-koan
.skm                                              application/x-koan
.skp                                              application/x-koan
.skt                                              application/x-koan
.sl                                               application/x-seelogo
.smi                                              application/smil
.smil                                             application/smil
.snd                                              audio/basic
.snd                                              audio/x-adpcm
.sol                                              application/solids
.spc                                              application/x-pkcs7-certificates
.spc                                              text/x-speech
.spl                                              application/futuresplash
.spr                                              application/x-sprite
.sprite                                           application/x-sprite
.src                                              application/x-wais-source
.ssi                                              text/x-server-parsed-html
.ssm                                              application/streamingmedia
.sst                                              application/vnd.ms-pki.certstore
.step                                             application/step
.stl                                              application/sla
.stl                                              application/vnd.ms-pki.stl
.stl                                              application/x-navistyle
.stp                                              application/step
.sv4cpio                                          application/x-sv4cpio
.sv4crc                                           application/x-sv4crc
.svf                                              image/vnd.dwg
.svf                                              image/x-dwg
.svr                                              application/x-world
.svr                                              x-world/x-svr
.swf                                              application/x-shockwave-flash
.t                                                application/x-troff
.talk                                             text/x-speech
.tar                                              application/x-tar
.tbk                                              application/toolbook
.tbk                                              application/x-tbook
.tcl                                              application/x-tcl
.tcl                                              text/x-script.tcl
.tcsh                                             text/x-script.tcsh
.tex                                              application/x-tex
.texi                                             application/x-texinfo
.texinfo                                          application/x-texinfo
.text                                             text/plain
.text                                             application/plain
.tgz                                              application/gnutar
.tgz                                              application/x-compressed
.tif                                              image/tiff
.tif                                              image/x-tiff
.tiff                                             image/tiff
.tiff                                             image/x-tiff
.tr                                               application/x-troff
.tsi                                              audio/tsp-audio
.tsp                                              application/dsptype
.tsp                                              audio/tsplayer
.tsv                                              text/tab-separated-values
.turbot                                           image/florian
.txt                                              text/plain
.uil                                              text/x-uil
.uni                                              text/uri-list
.unis                                             text/uri-list
.unv                                              application/i-deas
.uri                                              text/uri-list
.uris                                             text/uri-list
.ustar                                            application/x-ustar
.ustar                                            multipart/x-ustar
.uu                                               application/octet-stream
.uu                                               text/x-uuencode
.uue                                              text/x-uuencode
.vcd                                              application/x-cdlink
.vcs                                              text/x-vcalendar
.vda                                              application/vda
.vdo                                              video/vdo
.vew                                              application/groupwise
.viv                                              video/vivo
.viv                                              video/vnd.vivo
.vivo                                             video/vivo
.vivo                                             video/vnd.vivo
.vmd                                              application/vocaltec-media-desc
.vmf                                              application/vocaltec-media-file
.voc                                              audio/voc
.voc                                              audio/x-voc
.vos                                              video/vosaic
.vox                                              audio/voxware
.vqe                                              audio/x-twinvq-plugin
.vqf                                              audio/x-twinvq
.vql                                              audio/x-twinvq-plugin
.vrml                                             application/x-vrml
.vrml                                             model/vrml
.vrml                                             x-world/x-vrml
.vrt                                              x-world/x-vrt
.vsd                                              application/x-visio
.vst                                              application/x-visio
.vsw                                              application/x-visio
.w60                                              application/wordperfect6.0
.w61                                              application/wordperfect6.1
.w6w                                              application/msword
.wav                                              audio/wav
.wav                                              audio/x-wav
.wb1                                              application/x-qpro
.wbmp                                             image/vnd.wap.wbmp
.web                                              application/vnd.xara
.wiz                                              application/msword
.wk1                                              application/x-123
.wmf                                              windows/metafile
.wml                                              text/vnd.wap.wml
.wmlc                                             application/vnd.wap.wmlc
.wmls                                             text/vnd.wap.wmlscript
.wmlsc                                            application/vnd.wap.wmlscriptc
.word                                             application/msword
.wp                                               application/wordperfect
.wp5                                              application/wordperfect
.wp5                                              application/wordperfect6.0
.wp6                                              application/wordperfect
.wpd                                              application/wordperfect
.wpd                                              application/x-wpwin
.wq1                                              application/x-lotus
.wri                                              application/mswrite
.wri                                              application/x-wri
.wrl                                              application/x-world
.wrl                                              model/vrml
.wrl                                              x-world/x-vrml
.wrz                                              model/vrml
.wrz                                              x-world/x-vrml
.wsc                                              text/scriplet
.wsrc                                             application/x-wais-source
.wtk                                              application/x-wintalk
.x-png                                            image/png
.xbm                                              image/x-xbitmap
.xbm                                              image/x-xbm
.xbm                                              image/xbm
.xdr                                              video/x-amt-demorun
.xgz                                              xgl/drawing
.xif                                              image/vnd.xiff
.xl                                               application/excel
.xla                                              application/excel
.xla                                              application/x-excel
.xla                                              application/x-msexcel
.xlb                                              application/excel
.xlb                                              application/vnd.ms-excel
.xlb                                              application/x-excel
.xlc                                              application/excel
.xlc                                              application/vnd.ms-excel
.xlc                                              application/x-excel
.xld                                              application/excel
.xld                                              application/x-excel
.xlk                                              application/excel
.xlk                                              application/x-excel
.xll                                              application/excel
.xll                                              application/vnd.ms-excel
.xll                                              application/x-excel
.xlm                                              application/excel
.xlm                                              application/vnd.ms-excel
.xlm                                              application/x-excel
.xls                                              application/excel
.xls                                              application/vnd.ms-excel
.xls                                              application/x-excel
.xls                                              application/x-msexcel
.xlt                                              application/excel
.xlt                                              application/x-excel
.xlv                                              application/excel
.xlv                                              application/x-excel
.xlw                                              application/excel
.xlw                                              application/vnd.ms-excel
.xlw                                              application/x-excel
.xlw                                              application/x-msexcel
.xm                                               audio/xm
.xml                                              application/xml
.xml                                              text/xml
.xmz                                              xgl/movie
.xpix                                             application/x-vnd.ls-xpix
.xpm                                              image/x-xpixmap
.xpm                                              image/xpm
.xsr                                              video/x-amt-showrun
.xwd                                              image/x-xwd
.xwd                                              image/x-xwindowdump
.xyz                                              chemical/x-pdb
.z                                                application/x-compress
.z                                                application/x-compressed
.zip                                              application/zip
.zip                                              application/x-compressed
.zip                                              application/x-zip-compressed
.zip                                              multipart/x-zip
.zoo                                              application/octet-stream
.zsh                                              text/x-script.zsh
'''.strip().split('\n')
ext2mime_dict={}
for e, mime in [i.split() for i in ext2mime_table]:
	ext=e[1:]
	if not ext in ext2mime_dict:
		ext2mime_dict[ext]=mime

mime2ext_table='''
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet	.xlsx
application/vnd.openxmlformats-officedocument.spreadsheetml.template	.xltx
application/vnd.openxmlformats-officedocument.presentationml.template	.potx
application/vnd.openxmlformats-officedocument.presentationml.slideshow	.ppsx
application/vnd.openxmlformats-officedocument.presentationml.presentation	.pptx
application/vnd.openxmlformats-officedocument.presentationml.slide	.sldx
application/vnd.openxmlformats-officedocument.wordprocessingml.document	.docx
application/vnd.openxmlformats-officedocument.wordprocessingml.template	.dotx
application/vnd.ms-excel.addin.macroEnabled.12	.xlam
application/vnd.ms-excel.sheet.binary.macroEnabled.12	.xlsb
applicaiton/x-bytecode.python                     .pyc
application/acad                                  .dwg
application/arj                                   .arj
application/base64                                .mm
application/base64                                .mme
application/binhex                                .hqx
application/binhex4                               .hqx
application/book                                  .book
application/book                                  .boo
application/cdf                                   .cdf
application/clariscad                             .ccad
application/commonground                          .dp
application/drafting                              .drw
application/dsptype                               .tsp
application/dxf                                   .dxf
application/envoy                                 .evy
application/excel                                 .xls
application/excel                                 .xl
application/excel                                 .xla
application/excel                                 .xlb
application/excel                                 .xlc
application/excel                                 .xld
application/excel                                 .xlk
application/excel                                 .xll
application/excel                                 .xlm
application/excel                                 .xlt
application/excel                                 .xlv
application/excel                                 .xlw
application/fractals                              .fif
application/freeloader                            .frl
application/futuresplash                          .spl
application/gnutar                                .tgz
application/groupwise                             .vew
application/hlp                                   .hlp
application/hta                                   .hta
application/i-deas                                .unv
application/iges                                  .iges
application/iges                                  .igs
application/inf                                   .inf
application/java                                  .class
application/java-byte-code                        .class
application/lha                                   .lha
application/lzx                                   .lzx
application/mac-binary                            .bin
application/mac-binhex                            .hqx
application/mac-binhex40                          .hqx
application/mac-compactpro                        .cpt
application/macbinary                             .bin
application/marc                                  .mrc
application/mbedlet                               .mbd
application/mcad                                  .mcd
application/mime                                  .aps
application/mspowerpoint                          .ppt
application/mspowerpoint                          .pot
application/mspowerpoint                          .pps
application/mspowerpoint                          .ppz
application/msword                                .doc
application/msword                                .dot
application/msword                                .w6w
application/msword                                .wiz
application/msword                                .word
application/mswrite                               .wri
application/netmc                                 .mcp
application/octet-stream                          .rar
application/octet-stream                          .exe
application/octet-stream                          .a
application/octet-stream                          .arc
application/octet-stream                          .arj
application/octet-stream                          .bin
application/octet-stream                          .com
application/octet-stream                          .dump
application/octet-stream                          .lha
application/octet-stream                          .lhx
application/octet-stream                          .lzh
application/octet-stream                          .lzx
application/octet-stream                          .o
application/octet-stream                          .psd
application/octet-stream                          .saveme
application/octet-stream                          .uu
application/octet-stream                          .zoo
application/oda                                   .oda
application/pdf                                   .pdf
application/pkcs-12                               .p12
application/pkcs-crl                              .crl
application/pkcs10                                .p10
application/pkcs7-mime                            .p7c
application/pkcs7-mime                            .p7m
application/pkcs7-signature                       .p7s
application/pkix-cert                             .cer
application/pkix-cert                             .crt
application/pkix-crl                              .crl
application/plain                                 .text
application/postscript                            .ps
application/postscript                            .ai
application/postscript                            .eps
application/powerpoint                            .ppt
application/pro_eng                               .part
application/pro_eng                               .prt
application/ringing-tones                         .rng
application/rtf                                   .rtf
application/rtf                                   .rtx
application/sdp                                   .sdp
application/sea                                   .sea
application/set                                   .set
application/sla                                   .stl
application/smil                                  .smi
application/smil                                  .smil
application/solids                                .sol
application/sounder                               .sdr
application/step                                  .step
application/step                                  .stp
application/streamingmedia                        .ssm
application/toolbook                              .tbk
application/vda                                   .vda
application/vnd.fdf                               .fdf
application/vnd.hp-hpgl                           .hgl
application/vnd.hp-hpgl                           .hpg
application/vnd.hp-hpgl                           .hpgl
application/vnd.hp-pcl                            .pcl
application/vnd.ms-excel                          .xls
application/vnd.ms-excel                          .xlb
application/vnd.ms-excel                          .xlc
application/vnd.ms-excel                          .xll
application/vnd.ms-excel                          .xlm
application/vnd.ms-excel                          .xlw
application/vnd.ms-pki.certstore                  .sst
application/vnd.ms-pki.pko                        .pko
application/vnd.ms-pki.seccat                     .cat
application/vnd.ms-pki.stl                        .stl
application/vnd.ms-powerpoint                     .ppt
application/vnd.ms-powerpoint                     .pot
application/vnd.ms-powerpoint                     .ppa
application/vnd.ms-powerpoint                     .pps
application/vnd.ms-powerpoint                     .pwz
application/vnd.ms-project                        .mpp
application/vnd.nokia.configuration-message       .ncm
application/vnd.nokia.ringing-tone                .rng
application/vnd.rn-realmedia                      .rm
application/vnd.rn-realplayer                     .rnx
application/vnd.wap.wmlc                          .wmlc
application/vnd.wap.wmlscriptc                    .wmlsc
application/vnd.xara                              .web
application/vocaltec-media-desc                   .vmd
application/vocaltec-media-file                   .vmf
application/wordperfect                           .wp
application/wordperfect                           .wp5
application/wordperfect                           .wp6
application/wordperfect                           .wpd
application/wordperfect6.0                        .w60
application/wordperfect6.0                        .wp5
application/wordperfect6.1                        .w61
application/x-123                                 .wk1
application/x-aim                                 .aim
application/x-authorware-bin                      .aab
application/x-authorware-map                      .aam
application/x-authorware-seg                      .aas
application/x-bcpio                               .bcpio
application/x-binary                              .bin
application/x-binhex40                            .hqx
application/x-bsh                                 .bsh
application/x-bsh                                 .sh
application/x-bsh                                 .shar
application/x-bytecode.elisp                      .elc
application/x-bzip                                .bz
application/x-bzip2                               .bz2
application/x-bzip2                               .boz
application/x-cdf                                 .cdf
application/x-cdlink                              .vcd
application/x-chat                                .cha
application/x-chat                                .chat
application/x-cmu-raster                          .ras
application/x-cocoa                               .cco
application/x-compactpro                          .cpt
application/x-compress                            .z
application/x-compressed                          .zip
application/x-compressed                          .gz
application/x-compressed                          .tgz
application/x-compressed                          .z
application/x-conference                          .nsc
application/x-cpio                                .cpio
application/x-cpt                                 .cpt
application/x-csh                                 .csh
application/x-deepv                               .deepv
application/x-director                            .dcr
application/x-director                            .dir
application/x-director                            .dxr
application/x-dvi                                 .dvi
application/x-elc                                 .elc
application/x-envoy                               .env
application/x-envoy                               .evy
application/x-esrehber                            .es
application/x-excel                               .xls
application/x-excel                               .xla
application/x-excel                               .xlb
application/x-excel                               .xlc
application/x-excel                               .xld
application/x-excel                               .xlk
application/x-excel                               .xll
application/x-excel                               .xlm
application/x-excel                               .xlt
application/x-excel                               .xlv
application/x-excel                               .xlw
application/x-frame                               .mif
application/x-freelance                           .pre
application/x-gsp                                 .gsp
application/x-gss                                 .gss
application/x-gtar                                .gtar
application/x-gzip                                .gz
application/x-gzip                                .gzip
application/x-hdf                                 .hdf
application/x-helpfile                            .hlp
application/x-helpfile                            .help
application/x-httpd-imap                          .imap
application/x-ima                                 .ima
application/x-internett-signup                    .ins
application/x-inventor                            .iv
application/x-ip2                                 .ip
application/x-java-class                          .class
application/x-java-commerce                       .jcm
application/x-javascript                          .js
application/x-koan                                .skd
application/x-koan                                .skm
application/x-koan                                .skp
application/x-koan                                .skt
application/x-ksh                                 .ksh
application/x-latex                               .latex
application/x-latex                               .ltx
application/x-lha                                 .lha
application/x-lisp                                .lsp
application/x-livescreen                          .ivy
application/x-lotus                               .wq1
application/x-lotusscreencam                      .scm
application/x-lzh                                 .lzh
application/x-lzx                                 .lzx
application/x-mac-binhex40                        .hqx
application/x-macbinary                           .bin
application/x-magic-cap-package-1.0               .mc$
application/x-mathcad                             .mcd
application/x-meme                                .mm
application/x-midi                                .mid
application/x-midi                                .midi
application/x-mif                                 .mif
application/x-mix-transfer                        .nix
application/x-mplayer2                            .asx
application/x-msexcel                             .xls
application/x-msexcel                             .xla
application/x-msexcel                             .xlw
application/x-mspowerpoint                        .ppt
application/x-navi-animation                      .ani
application/x-navidoc                             .nvd
application/x-navimap                             .map
application/x-navistyle                           .stl
application/x-netcdf                              .cdf
application/x-netcdf                              .nc
application/x-newton-compatible-pkg               .pkg
application/x-nokia-9000-communicator-add-on-software    		.aos
application/x-omc                                 .omc
application/x-omcdatamaker                        .omcd
application/x-omcregerator                        .omcr
application/x-pagemaker                           .pm4
application/x-pagemaker                           .pm5
application/x-pcl                                 .pcl
application/x-pixclscript                         .plx
application/x-pkcs10                              .p10
application/x-pkcs12                              .p12
application/x-pkcs7-certificates                  .spc
application/x-pkcs7-certreqresp                   .p7r
application/x-pkcs7-mime                          .p7c
application/x-pkcs7-mime                          .p7m
application/x-pkcs7-signature                     .p7a
application/x-pointplus                           .css
application/x-portable-anymap                     .pnm
application/x-project                             .mpc
application/x-project                             .mpt
application/x-project                             .mpv
application/x-project                             .mpx
application/x-qpro                                .wb1
application/x-rtf                                 .rtf
application/x-sdp                                 .sdp
application/x-sea                                 .sea
application/x-seelogo                             .sl
application/x-sh                                  .sh
application/x-shar                                .shar
application/x-shar                                .sh
application/x-shockwave-flash                     .swf
application/x-sit                                 .sit
application/x-sprite                              .spr
application/x-sprite                              .sprite
application/x-stuffit                             .sit
application/x-sv4cpio                             .sv4cpio
application/x-sv4crc                              .sv4crc
application/x-tar                                 .tar
application/x-tbook                               .sbk
application/x-tbook                               .tbk
application/x-tcl                                 .tcl
application/x-tex                                 .tex
application/x-texinfo                             .texi
application/x-texinfo                             .texinfo
application/x-troff                               .roff
application/x-troff                               .t
application/x-troff                               .tr
application/x-troff-man                           .man
application/x-troff-me                            .me
application/x-troff-ms                            .ms
application/x-troff-msvideo                       .avi
application/x-ustar                               .ustar
application/x-visio                               .vsd
application/x-visio                               .vst
application/x-visio                               .vsw
application/x-vnd.audioexplosion.mzz              .mzz
application/x-vnd.ls-xpix                         .xpix
application/x-vrml                                .vrml
application/x-wais-source                         .src
application/x-wais-source                         .wsrc
application/x-winhelp                             .hlp
application/x-wintalk                             .wtk
application/x-world                               .svr
application/x-world                               .wrl
application/x-wpwin                               .wpd
application/x-wri                                 .wri
application/x-x509-ca-cert                        .cer
application/x-x509-ca-cert                        .crt
application/x-x509-ca-cert                        .der
application/x-x509-user-cert                      .crt
application/x-zip-compressed                      .zip
application/xml                                   .xml
application/zip                                   .zip
audio/aiff                                        .aiff
audio/aiff                                        .aif
audio/aiff                                        .aifc
audio/basic                                       .au
audio/basic                                       .snd
audio/it                                          .it
audio/make                                        .funk
audio/make                                        .my
audio/make                                        .pfunk
audio/make.my.funk                                .pfunk
audio/mid                                         .rmi
audio/midi                                        .mid
audio/midi                                        .kar
audio/midi                                        .midi
audio/mod                                         .mod
audio/mpeg                                        .mpg
audio/mpeg                                        .m2a
audio/mpeg                                        .mp2
audio/mpeg                                        .mpa
audio/mpeg                                        .mpga
audio/mpeg3                                       .mp3
audio/nspaudio                                    .la
audio/nspaudio                                    .lma
audio/s3m                                         .s3m
audio/tsp-audio                                   .tsi
audio/tsplayer                                    .tsp
audio/vnd.qcelp                                   .qcp
audio/voc                                         .voc
audio/voxware                                     .vox
audio/wav                                         .wav
audio/x-adpcm                                     .snd
audio/x-aiff                                      .aif
audio/x-aiff                                      .aiff
audio/x-aiff                                      .aifc
audio/x-au                                        .au
audio/x-gsm                                       .gsm
audio/x-gsm                                       .gsd
audio/x-jam                                       .jam
audio/x-liveaudio                                 .lam
audio/x-mid                                       .mid
audio/x-mid                                       .midi
audio/x-midi                                      .mid
audio/x-midi                                      .midi
audio/x-mod                                       .mod
audio/x-mpeg                                      .mp2
audio/x-mpeg-3                                    .mp3
audio/x-mpequrl                                   .m3u
audio/x-nspaudio                                  .la
audio/x-nspaudio                                  .lma
audio/x-pn-realaudio                              .ra
audio/x-pn-realaudio                              .ram
audio/x-pn-realaudio                              .rm
audio/x-pn-realaudio                              .rmm
audio/x-pn-realaudio                              .rmp
audio/x-pn-realaudio-plugin                       .ra
audio/x-pn-realaudio-plugin                       .rmp
audio/x-pn-realaudio-plugin                       .rpm
audio/x-psid                                      .sid
audio/x-realaudio                                 .ra
audio/x-twinvq                                    .vqf
audio/x-twinvq-plugin                             .vqe
audio/x-twinvq-plugin                             .vql
audio/x-vnd.audioexplosion.mjuicemediafile        .mjf
audio/x-voc                                       .voc
audio/x-wav                                       .wav
audio/xm                                          .xm
chemical/x-pdb                                    .pdb
chemical/x-pdb                                    .xyz
drawing/x-dwf                                     .dwf
i-world/i-vrml                                    .ivr
image/bmp                                         .bmp
image/bmp                                         .bm
image/cmu-raster                                  .ras
image/cmu-raster                                  .rast
image/fif                                         .fif
image/florian                                     .flo
image/florian                                     .turbot
image/g3fax                                       .g3
image/gif                                         .gif
image/ief                                         .ief
image/ief                                         .iefs
image/jpeg                                        .jpg
image/jpeg                                        .jfif
image/jpeg                                        .jfif-tbnl
image/jpeg                                        .jpe
image/jpeg                                        .jpeg
image/jutvision                                   .jut
image/naplps                                      .nap
image/naplps                                      .naplps
image/pict                                        .pic
image/pict                                        .pict
image/pjpeg                                       .jpeg
image/pjpeg                                       .jfif
image/pjpeg                                       .jpe
image/pjpeg                                       .jpg
image/png                                         .png
image/png                                         .x-png
image/tiff                                        .tiff
image/tiff                                        .tif
image/vasa                                        .mcf
image/vnd.dwg                                     .dwg
image/vnd.dwg                                     .dxf
image/vnd.dwg                                     .svf
image/vnd.fpx                                     .fpx
image/vnd.net-fpx                                 .fpx
image/vnd.rn-realflash                            .rf
image/vnd.rn-realpix                              .rp
image/vnd.wap.wbmp                                .wbmp
image/vnd.xiff                                    .xif
image/x-cmu-raster                                .ras
image/x-dwg                                       .dwg
image/x-dwg                                       .dxf
image/x-dwg                                       .svf
image/x-icon                                      .ico
image/x-jg                                        .art
image/x-jps                                       .jps
image/x-niff                                      .nif
image/x-niff                                      .niff
image/x-pcx                                       .pcx
image/x-pict                                      .pct
image/x-portable-anymap                           .pnm
image/x-portable-bitmap                           .pbm
image/x-portable-graymap                          .pgm
image/x-portable-greymap                          .pgm
image/x-portable-pixmap                           .ppm
image/x-quicktime                                 .qif
image/x-quicktime                                 .qti
image/x-quicktime                                 .qtif
image/x-rgb                                       .rgb
image/x-tiff                                      .tiff
image/x-tiff                                      .tif
image/x-windows-bmp                               .bmp
image/x-xbitmap                                   .xbm
image/x-xbm                                       .xbm
image/x-xpixmap                                   .pm
image/x-xpixmap                                   .xpm
image/x-xwd                                       .xwd
image/x-xwindowdump                               .xwd
image/xbm                                         .xbm
image/xpm                                         .xpm
message/rfc822                                    .mht
message/rfc822                                    .mhtml
message/rfc822                                    .mime
model/iges                                        .iges
model/iges                                        .igs
model/vnd.dwf                                     .dwf
model/vrml                                        .vrml
model/vrml                                        .wrl
model/vrml                                        .wrz
model/x-pov                                       .pov
multipart/x-gzip                                  .gzip
multipart/x-ustar                                 .ustar
multipart/x-zip                                   .zip
music/crescendo                                   .mid
music/crescendo                                   .midi
music/x-karaoke                                   .kar
paleovu/x-pv                                      .pvu
text/asp                                          .asp
text/css                                          .css
text/html                                         .html
text/html                                         .acgi
text/html                                         .htm
text/html                                         .htmls
text/html                                         .htx
text/html                                         .shtml
text/mcf                                          .mcf
text/pascal                                       .pas
text/plain                                        .txt
text/plain                                        .c
text/plain                                        .c++
text/plain                                        .cc
text/plain                                        .com
text/plain                                        .conf
text/plain                                        .cxx
text/plain                                        .def
text/plain                                        .f
text/plain                                        .f90
text/plain                                        .for
text/plain                                        .g
text/plain                                        .h
text/plain                                        .hh
text/plain                                        .idc
text/plain                                        .jav
text/plain                                        .java
text/plain                                        .list
text/plain                                        .log
text/plain                                        .lst
text/plain                                        .m
text/plain                                        .mar
text/plain                                        .pl
text/plain                                        .sdml
text/plain                                        .text
text/richtext                                     .rt
text/richtext                                     .rtf
text/richtext                                     .rtx
text/scriplet                                     .wsc
text/sgml                                         .sgml
text/sgml                                         .sgm
text/tab-separated-values                         .tsv
text/uri-list                                     .uni
text/uri-list                                     .unis
text/uri-list                                     .uri
text/uri-list                                     .uris
text/vnd.abc                                      .abc
text/vnd.fmi.flexstor                             .flx
text/vnd.rn-realtext                              .rt
text/vnd.wap.wml                                  .wml
text/vnd.wap.wmlscript                            .wmls
text/webviewhtml                                  .htt
text/x-asm                                        .asm
text/x-asm                                        .s
text/x-audiosoft-intra                            .aip
text/x-c                                          .c
text/x-c                                          .cc
text/x-c                                          .cpp
text/x-component                                  .htc
text/x-fortran                                    .f
text/x-fortran                                    .f77
text/x-fortran                                    .f90
text/x-fortran                                    .for
text/x-h                                          .h
text/x-h                                          .hh
text/x-java-source                                .java
text/x-java-source                                .jav
text/x-la-asf                                     .lsx
text/x-m                                          .m
text/x-pascal                                     .p
text/x-script                                     .hlb
text/x-script.csh                                 .csh
text/x-script.elisp                               .el
text/x-script.guile                               .scm
text/x-script.ksh                                 .ksh
text/x-script.lisp                                .lsp
text/x-script.perl                                .pl
text/x-script.perl-module                         .pm
text/x-script.phyton                              .py
text/x-script.rexx                                .rexx
text/x-script.scheme                              .scm
text/x-script.sh                                  .sh
text/x-script.tcl                                 .tcl
text/x-script.tcsh                                .tcsh
text/x-script.zsh                                 .zsh
text/x-server-parsed-html                         .shtml
text/x-server-parsed-html                         .ssi
text/x-setext                                     .etx
text/x-sgml                                       .sgml
text/x-sgml                                       .sgm
text/x-speech                                     .spc
text/x-speech                                     .talk
text/x-uil                                        .uil
text/x-uuencode                                   .uu
text/x-uuencode                                   .uue
text/x-vcalendar                                  .vcs
text/xml                                          .xml
video/animaflex                                   .afl
video/avi                                         .avi
video/avs-video                                   .avs
video/dl                                          .dl
video/fli                                         .fli
video/gl                                          .gl
video/mpeg                                        .mpg
video/mpeg                                        .m1v
video/mpeg                                        .m2v
video/mpeg                                        .mp2
video/mpeg                                        .mp3
video/mpeg                                        .mpa
video/mpeg                                        .mpe
video/mpeg                                        .mpeg
video/msvideo                                     .avi
video/quicktime                                   .mov
video/quicktime                                   .moov
video/quicktime                                   .qt
video/vdo                                         .vdo
video/vivo                                        .viv
video/vivo                                        .vivo
video/vnd.rn-realvideo                            .rv
video/vnd.vivo                                    .viv
video/vnd.vivo                                    .vivo
video/vosaic                                      .vos
video/x-amt-demorun                               .xdr
video/x-amt-showrun                               .xsr
video/x-atomic3d-feature                          .fmf
video/x-dl                                        .dl
video/x-dv                                        .dif
video/x-dv                                        .dv
video/x-fli                                       .fli
video/x-gl                                        .gl
video/x-isvideo                                   .isu
video/x-motion-jpeg                               .mjpg
video/x-mpeg                                      .mp3
video/x-mpeg                                      .mp2
video/x-mpeq2a                                    .mp2
video/x-ms-asf                                    .asf
video/x-ms-asf                                    .asx
video/x-ms-asf-plugin                             .asx
video/x-msvideo                                   .avi
video/x-qtc                                       .qtc
video/x-scm                                       .scm
video/x-sgi-movie                                 .mv
video/x-sgi-movie                                 .movie
windows/metafile                                  .wmf
www/mime                                          .mime
x-conference/x-cooltalk                           .ice
x-music/x-midi                                    .mid
x-music/x-midi                                    .midi
x-world/x-3dmf                                    .3dm
x-world/x-3dmf                                    .3dmf
x-world/x-3dmf                                    .qd3
x-world/x-3dmf                                    .qd3d
x-world/x-svr                                     .svr
x-world/x-vrml                                    .vrml
x-world/x-vrml                                    .wrl
x-world/x-vrml                                    .wrz
x-world/x-vrt                                     .vrt
xgl/drawing                                       .xgz
xgl/movie                                         .xmz
'''.strip().split('\n')





mime2ext_dict={}
for mime, e in [i.strip().split() for i in mime2ext_table]:
	ext=e[1:]
	if not mime in mime2ext_dict:
		mime2ext_dict[mime]=ext

def get_mimetype_by_ext(ext, default=''):
	return ext2mime_dict.get(ext.lower(), default)
	
def get_ext_by_mimetype(mime, default=''):
	return mime2ext_dict.get(mime.lower(), default)
	
if __name__=='__main__':
	for i in 'html jpg gif pdf'.split():
		print get_mimetype_by_ext(i)
	while 1:
		print get_mimetype_by_ext(raw_input())
