#!/usr/bin/env python
from libjade import *

tmp_cmake_file='''cmake_minimum_required(VERSION 2.6)
# add_subdirectory(src bin)
project (jadesoul)

find_package(Boost REQUIRED)
set(Boost_USE_STATIC_LIBS ON)

include_directories(${Boost_INCLUDE_DIRS})
link_directories(${Boost_LIBRARY_DIRS})

# set (SRCS jadesoul.cpp)
aux_source_directory(. SRCS)
# set (UNIT_TEST_SRCS unit_test.cpp)
# set (CMAKE_EXE_LINKER_FLAGS -lboost_iostreams)

add_executable (jadesoul ${SRCS})

# add_custom_command(
	# TARGET jadesoul
	# POST_BUILD
	# COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/jadesoul
	# WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	# COMMENT "Postbuild action"
# )'''

cmake_file_name='CMakeLists.txt'
if not exists(cmake_file_name):
	fwrite(tmp_cmake_file, cmake_file_name)
	run('n '+cmake_file_name)
