#!/usr/bin/env python
import sys, datetime, os, time

fn=sys.argv[1].strip()
if fn.find('.')==-1: fn+='.cpp'

macro=fn.replace('.', '_').upper()+('_%s' % time.time()).replace('.', '_')
ifdef='#ifndef %s\n#define %s\n' % (macro, macro)
endif='#endif /* %s */\n' % macro

s='''/**
 * File: '''+fn+'''
 * Description: 
 *
 * Copyright (c) 2012 Jadesoul (Home Page: http://jadesoul.sinaapp.com)
 * 
 * Date: '''+str(datetime.datetime.now())+'''
 * Written In: Peking University, beijing, China
 */

#include <jadesoul.hpp>

int main () {
	cout<<"hello, world"<<endl;
}

'''
if fn[fn.rfind('.')+1]=='h': 
	s=ifdef+s+endif

f=open(fn, 'w')
f.write(s)
f.close()
os.system('n "'+fn+'"')
