#!/usr/bin/env python
import sys, datetime, os

if len(sys.argv)<2: fn='__init__'
else: fn=sys.argv[1].strip()
if fn.find('.')==-1: fn+='.py'


f=open(fn, 'w')
f.write('''#!/usr/bin/python
#coding:utf8

from libjade import *



if __name__=='__main__':
	pass

''')
f.close()
os.system('vi "'+fn+'"')
